[project]
name = "docutranslate"
version = "0.1.9"
description = "文件翻译工具"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
        "docling>=2.31.0",
        "httpx",
        "markdown2",
        "fastapi[standard]>=0.115.12",
        "nuitka>=2.7.2",
]
