[project]
name = "docutranslate"
version = "0.1.6"
description = "文件翻译工具"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docling",
    "httpx",
    "markdown2",
    "mdformat>=0.7.22",
    "transformers>=4.50.1",
]
